Algoritmo "Enquanto Teste"

Var

         x, soma : real

Inicio
            escreva ("Digite um número: ")
            leia (x)
            
            soma <- 0
            
            enquanto x <> 0 faca
                     soma <- soma + x
                     escreva ("Digite um número: ")
                     leia (x)
            fimenquanto
            
            
            escreval
            escreva ("SOMA = ", soma)

Fimalgoritmo