Algoritmo "Exponênciação e Raíz"

Var
    a, b, c, d, x, y, z : real

Inicio

     escreva ("Digite o número base: ")
     leia (a)
     escreva ("Digite o número exponêncial: ")
     leia (b)
     x <- exp (a,b)
     escreval ("Resultado: ", x)
     escreval
     escreval
     escreva ("Digite o radicando: ")
     leia (c)
     y <- raizq (c)
     escreva ("A Raíz de", c, " é: ", y)
     

Fimalgoritmo