Algoritmo "Teste enquanto 2"

Var

             x, y : real

Inicio

             x <- 10
             y <- 0
             
             enquanto x > 2 faca

                      y <- y + x
                      x <- x - 1
                      
                      escreval ("valor de X: ", x)
                      escreval ("Valor de Y: ", y)
             
             
             fimenquanto

Fimalgoritmo